[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "../backend/netlify-functions"
  node_bundler = "esbuild"

[functions.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-functions-install-core" 